### ISSUE TITLE
"The "--gql-coverage" option does not exist" when running in parallel

### ISSUE THREAD

**Issue by Saarnaki** [worksome/pest-graphql-coverage#10]
When running tests in parallel mode (`php artisan test -p --gql-coverage`) the following error message is stated:

```
The "--gql-coverage" option does not exist.
``` 

Works fine with sequential.

**Comment by owenvoke** [comment]
Apologies for the really delayed reply on this... Try putting the `-p` option as the last option.
```shell
php artisan test --gql-coverage -p
```

**Comment by Saarnaki** [comment]
Yep, in that order it works. Thanks!
Would be a good idea to change it also in the Readme.
